# Generated by Django 3.1.2 on 2020-10-20 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration_profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=registration_profiles.models.code_generator, max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reg_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
